### ISSUE TITLE
can not start nydus container

### ISSUE THREAD

**Issue by kevinXYin** [dragonflyoss/image-service#874] opened 2022-11-18 08:46 UTC
I run snapshotter with follow cmd manually

`/path_to_snapshotter/nydus-snapshotter/bin/containerd-nydus-grpc  --config-path /path_to_config/nydus-erofs-config.json  --daemon-mode shared  --daemon-backend fscache  --log-level info  --root /var/lib/containerd/io.containerd.snapshotter.v1.nydus  --cache-dir /var/lib/nydus/cache  --address /run/containerd/containerd-nydus-grpc.sock  --nydusd-path /path_to_nydusd/image-service/target/release/nydusd  --nydusimg-path /path_to_nydusd/image-service/target/release/  --log-to-stdout  --nydusd-thread-num 4`

config:
`{
  "type": "bootstrap",
  "config": {
    "backend_type": "registry",
    "backend_config": {
      "scheme": "https",
      "timeout": 3,
      "connect_timeout": 3,
      "retry_limit": 2
    },
    "cache_type": "fscache",
    "prefetch_config": {
      "enable": true,
      "threads_count": 5,
      "merging_size": 1048576
    }
  },
  "mode":"direct",
  "digest_validate": false,
  "iostat_files": false,
  "enable_xattr": true
}`

After restart snapshotter manually , I found can not start a nydus container ,  and get follow errors:

`FATA[0003] mount file system by daemon cdrk9paq4e9kuti3dl5g, snapshot 40: failed to mount: failed to share mount: failed to create new nydus client: stat /var/lib/containerd/io.containerd.snapshotter.v1.nydus/socket/cdrk9paq4e9kuti3dl5g/api.sock: no such file or directory: unknown `

snapshotter logs:

`INFO[2022-11-18T16:40:05.883729680+08:00] found nydus meta layer id 40                  key=default/44/32417ba76ffd29cd34663dcdb5b74623d6f663d6fb2aa50a5129c17b7cee9cb3 parent="default/42/sha256:6fa694ee4fcde98c2e82d75315d64fec0fb148dae6df66a73a97d1437cc9c7be"
INFO[2022-11-18T16:40:05.883750632+08:00] prepare remote snapshot mountpoint /var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/40/fs 
WARN[2022-11-18T16:40:05.885378166+08:00] daemon daemon_id=cdrk9paq4e9kuti3dl5g is not found 
INFO[2022-11-18T16:40:08.929268151+08:00] remove snapshot with key default/43//tmp/initialC3104703466 snapshot id 41 
INFO[2022-11-18T16:40:08.932096836+08:00] remove snapshot with key default/44/32417ba76ffd29cd34663dcdb5b74623d6f663d6fb2aa50a5129c17b7cee9cb3 snapshot id 42 
`

**Comment by changweige** [comment] 2022-11-21 02:57
Could you please share your nydus-snapshotter version too?

**Comment by kevinXYin** [comment] 2022-11-21 12:20
nydusd-snapshotter  master head  03c82d3

**Comment by changweige** [comment] 2022-11-21 12:24
I guess it is caused by the fact that nydus-snapshotter does not retain the shared daemon pointer to FS layer during daemon recovering. I will fix it.

**Comment by changweige** [comment] 2022-11-22 09:33
will be resolved by https://github.com/containerd/nydus-snapshotter/pull/260

**Comment by changweige** [comment] 2023-01-16 09:55
already fixed

**Closed by changweige** 2023-01-16 09:55 UTC
