### ISSUE TITLE
can not start a rafs v6 container in fuse mode with --shared-daemon option

### ISSUE THREAD

**Issue by kevinXYin** [dragonflyoss/image-service#638] opened 2022-08-03 09:09 UTC
I run containerd-nydus-grpc with below cmd
 ``containerd-nydus-grpc \
    --config-path /etc/nydusd-config.json \
    --shared-daemon \
    --log-level info \
    --root /var/lib/containerd/io.containerd.snapshotter.v1.nydus \
    --cache-dir /var/lib/nydus/cache \
    --address /run/containerd/containerd-nydus-grpc.sock \
    .....``

then try to start a rafs v6 container with nerdctl , but get error 
`FATA[0000] failed to mount /run/user/0/containerd-mount2787954349: no such file or directory 
`
dmesg 
`overlayfs: failed to resolve '/var/lib/containerd/io.containerd.snapshotter.v1.nydus/mnt/362/fs': -2
`

And I do the following test
1. with same containerd-nydus-grpc cmd , start a rafs v5 container --- pass
2. remove --shared-daemon option , start the same rafs v6 container --- pass
3. launch containerd-nydus-grpc with fscache mode, start the same rafs v6 container --- pass

**Comment by changweige** [comment] 2022-08-17 08:54
There is an excellent chance that this issue relates to https://github.com/containerd/nydus-snapshotter/pull/132. Could you please help reproduce the problem with the latest nydus-snapshotter mainline code?

**Comment by changweige** [comment] 2022-09-26 10:35
Recent nydus-snapshotter improvements should fix this issue, can we close it now?

**Comment by changweige** [comment] 2022-09-30 07:27
Let's close it since nydus-snapshotter should already fix it.

**Closed by changweige** 2022-09-30 07:27 UTC
