### ISSUE TITLE
【bug】nydusify pack can not save the blob file to the root path of oss bucket

### ISSUE THREAD

**Issue by zhangshuiyong** [dragonflyoss/image-service#608] opened 2022-07-25 08:27 UTC
**nydus Version:**
2.1.0-alpha2

**oss-backend-config.json:** 
<img width="439" alt="image" src="https://user-images.githubusercontent.com/1655233/180732044-e9c163c6-f322-43c9-a44b-2c952accc4ed.png">

**log:**
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1655233/180732441-3c548813-5b7a-47e7-9570-f05e3c6ed09a.png">

**Code:**
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1655233/180732695-fcf12fc0-d6a4-44dd-b2a4-35580d9d6f43.png">

**Bug result: it will create a folder name "/" , then save the blob file into the folder.**

<img width="423" alt="image" src="https://user-images.githubusercontent.com/1655233/180732778-be37ab4e-4d09-4a3e-8423-80ca6f2e9d52.png">

**Comment by imeoer** [comment] 2022-07-25 08:50
![image](https://user-images.githubusercontent.com/1524576/180736854-6c578771-781d-47c3-aa00-f0e73bbed982.png)

Thanks for reporting, it looks like the root cause is here.

**Comment by ccx1024cc** [comment] 2022-10-14 01:17
@zhangshuiyong Nydus use specified prefix directly, instead of with `/` suffix. Files are not in `root` with empty prefix now. If u want, specify prefix = `/`.

**Comment by imeoer** [comment] 2022-11-18 06:23
@zhangshuiyong Fixed in `v2.1.1` release.

**Closed by imeoer** 2022-11-18 06:23 UTC
